
services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-portfolio
    ports:
      - "8888:8888"
    volumes:
      # ALTERAÇÃO AQUI:
      # Apontamos para a raiz (./) para que o container veja as pastas 'data', 'notebooks' e 'output'
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS='-R'
    restart: unless-stopped